"""Update user and form entry properties

Revision ID: 6f36efa69a00
Revises: d14ecfcd7ffa
Create Date: 2022-07-19 15:29:55.961731

"""

# revision identifiers, used by Alembic.
revision = '6f36efa69a00'
down_revision = 'd14ecfcd7ffa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_encounters', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('patient_encounters', sa.Column('patient_encounter_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('patient_encounters_patient_incident_uuid_key', 'patient_encounters', type_='unique')
    op.drop_constraint('patient_encounters_user_uuid_key', 'patient_encounters', type_='unique')
    op.create_unique_constraint(None, 'patient_encounters', ['patient_encounter_uuid'])
    op.drop_column('patient_encounters', 'patient_incident_uuid')
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    op.add_column('patient_encounters', sa.Column('patient_incident_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patient_encounters', type_='unique')
    op.create_unique_constraint('patient_encounters_user_uuid_key', 'patient_encounters', ['user_uuid'])
    op.create_unique_constraint('patient_encounters_patient_incident_uuid_key', 'patient_encounters', ['patient_incident_uuid'])
    op.drop_column('patient_encounters', 'patient_encounter_uuid')
    op.drop_column('patient_encounters', 'deleted')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass