"""CHANGEME

Revision ID: d14ecfcd7ffa
Revises: 676c96a21e88
Create Date: 2022-07-18 21:32:34.224408

"""

# revision identifiers, used by Alembic.
revision = 'd14ecfcd7ffa'
down_revision = '676c96a21e88'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_encounters', sa.Column('document_num', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('patient_rfid', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('location', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('triage_acuity', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('chief_complaints', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('arrival_time', sa.DateTime(), nullable=True))
    op.add_column('patient_encounters', sa.Column('departure_time', sa.DateTime(), nullable=True))
    op.add_column('patient_encounters', sa.Column('departure_dest', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('handover_from', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('patient_encounters', sa.Column('handover_too', sa.String(), nullable=True))
    op.add_column('patient_encounters', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('patient_encounters', 'presenting_complaint')
    op.drop_column('patient_encounters', 'document_number')
    op.drop_column('patient_encounters', 'rfid')
    op.drop_column('patient_encounters', 'departure_timestamp')
    op.drop_column('patient_encounters', 'arrival_timestamp')
    op.drop_column('patient_encounters', 'triage_category')
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_encounters', sa.Column('triage_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_encounters', sa.Column('arrival_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('patient_encounters', sa.Column('departure_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('patient_encounters', sa.Column('rfid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_encounters', sa.Column('document_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_encounters', sa.Column('presenting_complaint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_encounters', 'comment')
    op.drop_column('patient_encounters', 'handover_too')
    op.drop_column('patient_encounters', 'date')
    op.drop_column('patient_encounters', 'handover_from')
    op.drop_column('patient_encounters', 'departure_dest')
    op.drop_column('patient_encounters', 'departure_time')
    op.drop_column('patient_encounters', 'arrival_time')
    op.drop_column('patient_encounters', 'chief_complaints')
    op.drop_column('patient_encounters', 'triage_acuity')
    op.drop_column('patient_encounters', 'location')
    op.drop_column('patient_encounters', 'patient_rfid')
    op.drop_column('patient_encounters', 'document_num')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass