"""Initial schema

Revision ID: 676c96a21e88
Revises: None
Create Date: 2022-07-11 04:36:44.920002

"""

# revision identifiers, used by Alembic.
revision = '676c96a21e88'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_encounters',
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_incident_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('rfid', sa.String(), nullable=True),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('arrival_method', sa.String(), nullable=True),
    sa.Column('on_shift', sa.Boolean(), nullable=True),
    sa.Column('triage_category', sa.String(), nullable=True),
    sa.Column('presenting_complaint', sa.String(), nullable=True),
    sa.Column('arrival_timestamp', sa.DateTime(), nullable=True),
    sa.Column('departure_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_incident_uuid'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_index(op.f('ix_patient_encounters_id'), 'patient_encounters', ['id'], unique=False)
    op.create_table('users',
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patient_encounters_id'), table_name='patient_encounters')
    op.drop_table('patient_encounters')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass