export const MFPEFormData = {
    patient_rfid: '',
    document_num: '',
    location: "Main Medical",
    handover_from: '',
    arrival_date: new Date,
    arrival_time: new Date,
    triage_acuity: '',
    age: new Number,
    gender: '',
    on_shift: '',
    chief_complaints: [],
    arrival_method: '',
    handover_too: '',
    departure_time: null,
    departure_date: null,
    departure_dest: '',
    comment: '',
};

export const chiefComplaints = [
    'Nausea/Vomiting',
    'Dizziness/Presyncope/Lightheaded',
    'Loss of Consciousness',
    'Seizure',
    'Adverse Drug Effect',
    'Agitation' ,
    'Bizarre Behaviour' ,
    'Hallucinations' ,
    'Anxiety' ,
    'Abdominal Pain',
    'Chest Pain' ,
    'Headache' ,
    'Other Pain' ,
    'Shortness of Breath',
    'Allergic Reaction',
    'Trauma',
];