version: '3.9'

# LOCAL DEV

services:
  api:
    container_name: api
    user: 1000:1000
    build:
      context: app/api/
      dockerfile: Dockerfile
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 5000:5000
    command: uvicorn api.main.app:api --reload --host=0.0.0.0 --port=5000
    volumes:
      # Mount local codebase to reflect changes for local dev
      - ./app/api:/app/api
    healthcheck:
      test: [ "CMD", "curl", "localhost:5000/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - migs
      - testapi

  migs:
    container_name: migs
    build:
      context: app/api/
      dockerfile: Dockerfile
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    command: bash -c "cd /app/api && alembic upgrade head"
    volumes:
      # Mount local codebase to reflect changes for local dev
      - ./app/api:/app/api
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    user: postgres
    image: postgres:13.2-alpine
    restart: always
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  testapi:
    container_name: testapi
    user: 1000:1000
    build:
      context: app/api/
      dockerfile: Dockerfile
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    # run as module so basedir (root) is added to python path
    command: python -m pytest api/tests/
    volumes:
      - ./app/api/:/app/api
    depends_on:
      - migs

  web:
    container_name: web
    user: node
    build:
      context: app/web/
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app/web:/code
    ports:
      - 3000:3000
    depends_on:
      - api

networks:
  default:
    driver: "bridge"
