version: '3.9'

# LOCAL DEV

services:
  api:
    container_name: api
    user: 1000:1000
    build:
      context: app/api/
      dockerfile: Dockerfile
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=example
      - FRONTEND_ORIGIN=localhost:3000
      - SECRET_KEY=space-pantz
    ports:
      - 5000:5000
    command: uvicorn api:example_api --reload --host=0.0.0.0 --port=5000
    volumes:
      # Mount local codebase to reflect changes for local dev
      - ./app/api:/app
    healthcheck:
      test: [ "CMD", "curl", "localhost:5000/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - migrations
      - testapi

  migrations:
    container_name: migs
    build:
      context: app/api/
      dockerfile: Dockerfile
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    command: alembic upgrade head
    volumes:
      # Mount local codebase to reflect changes for local dev
      - ./app/api:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:13.2-alpine
    restart: always
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  testapi:
    container_name: testapi
    user: 1000:1000
    build:
      context: app/api/
      dockerfile: Dockerfile
    env_file: app/api/.env
    environment:
      - POSTGRES_HOST=db
    # run as module so basedir (root) is added to python path
    command: python -m pytest tests/
    volumes:
      - ./app/api/:/app
    depends_on:
      - migrations

  web:
    container_name: web
    user: 1000:1000
    build:
      context: app/web/
      dockerfile: Dockerfile    
      target: development
    volumes:
      - ./app/web:/code
    ports:
      - 3000:3000
    depends_on:
      - api


networks:
  default:
    driver: "bridge"
