"""CHANGEME

Revision ID: fb0a338656b7
Revises: 
Create Date: 2024-01-29 23:32:08.346008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb0a338656b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intakes',
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('intake_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('guest_rfid', sa.String(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_method', sa.String(), nullable=True),
    sa.Column('identified_gender', sa.String(), nullable=True),
    sa.Column('first_visit', sa.Boolean(), nullable=True),
    sa.Column('presenting_complaint', sa.String(), nullable=True),
    sa.Column('guest_consciousness_level', sa.String(), nullable=True),
    sa.Column('guest_emotional_state', sa.String(), nullable=True),
    sa.Column('substance_categories', sa.String(), nullable=True),
    sa.Column('time_since_last_dose', sa.Integer(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_time', sa.DateTime(), nullable=True),
    sa.Column('discharge_method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('intake_uuid'),
    sa.UniqueConstraint('intake_uuid')
    )
    op.create_table('users',
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('intakes')
    # ### end Alembic commands ###
