"""CHANGEME

Revision ID: 5a6e3d13358f
Revises: 38ecd95d6104
Create Date: 2024-03-22 18:05:23.388169

"""
from alembic import op
import sqlalchemy as sa

from alembic import context

# revision identifiers, used by Alembic.
revision = '5a6e3d13358f'
down_revision = '38ecd95d6104'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakes', sa.Column('document_num', sa.String(), nullable=True))
    op.add_column('intakes', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intakes', 'comment')
    op.drop_column('intakes', 'document_num')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass