#!/bin/bash
set -e

# Create Medical database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$POSTGRES_MEDICAL_DB";
EOSQL

# Create Sanctuary database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$POSTGRES_SANCTUARY_DB";
EOSQL

# Create a test database for the Medical app
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "${POSTGRES_MEDICAL_DB}_test";
EOSQL

# Create a test database for the Sanctuary app
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "${POSTGRES_SANCTUARY_DB}_test";
EOSQL

# Create a new user for the Medical database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_MEDICAL_USER WITH ENCRYPTED PASSWORD '$POSTGRES_MEDICAL_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_MEDICAL_DB" TO $POSTGRES_MEDICAL_USER;
  GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_MEDICAL_DB}_test" TO $POSTGRES_MEDICAL_USER;
EOSQL

# Create a new user for the Sanctuary database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_SANCTUARY_USER WITH ENCRYPTED PASSWORD '$POSTGRES_SANCTUARY_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_SANCTUARY_DB" TO $POSTGRES_SANCTUARY_USER;
  GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_SANCTUARY_DB}_test" TO $POSTGRES_SANCTUARY_USER;
EOSQL
