#Dockerfile for production build, web
FROM node:18-alpine
 
# user the default user the container comes with
RUN mkdir /code && chown -R node:node /code
WORKDIR /code

USER node

# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install

# Copy app files
COPY . .

#builds with production env
RUN yarn build

# Expose port
EXPOSE 3000

#Start the app
CMD ["yarn", "start"]
