#Dockerfile for development build, web
FROM node:18-alpine 

# user the default user the container comes with
RUN mkdir /code && chown -R node:node /code
WORKDIR /code

USER node

# Cache and Install dependencies
COPY package.json .

# Copy app files
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD yarn install && yarn dev
