name: Build and Push Web

on:
  push:
    branches: 
      - main
    paths:
      - 'app/web/**'
  pull_request:
    types:
      -opened
    branches: 
      - main
    paths:
      - 'app/web/**'

env:
  TAG: prod
  GAR: ${{ secrets.ARTIFACT_REGISTRY }}

jobs:
  build-and-push-web:
    name: build-and-push-web
    runs-on: ubuntu-20.04
      
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with: 
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
        
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ARTIFACT_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: build-tag-push
        run: |
              export GAR=${{ env.GAR }}
              make build-push-web ${{ env.TAG }}
