name: Build

on:
  push:

env:
  IMAGE: fastapi-example
  TAG: dev
  SERVICE_CONTEXT: app/api/
  DOCKERFILE: .Dockerfile

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build n Tag
        run: |
          cd ${{ env.SERVICE_CONTEXT }}
          docker build -f ${{ env.DOCKERFILE }} -t ${{ env.IMAGE }}:${{ env.TAG }} .