name: Build

on:
  push:

env:
  IMAGE: fastapi-example
  TAG: dev
  SERVICE_CONTEXT: app/

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    #   - name: Login
    #     run: |
    #       docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }} ${{ secrets.REGISTRY_HOST }}
      - name: Build n Tag
        run: |
          cd ${{ env.SERVICE_CONTEXT }}
          docker build -t ${{ env.IMAGE }}:${{ env.TAG }} .
    # - name: Push
    #   run: |
    #     docker push --all-tags ${{ secrets.REGISTRY_HOST }}/${{ secrets.IS_NAMESPACE }}/${{ env.IMAGE }}